### ISSUE TITLE
How to use H2 instead of MySQL?

### ISSUE THREAD

**Issue by cabalamat** [pedrorijo91/play-slick3-steps#1]
I was wondering if it would be possible to use H2 for this instead of mySQL? One advantage of H2 is that because it is a Java in-memory database, it does not require the setting up of an extra program to get the web app running (unlike MySQL).

I tried to get it working with H2 by putting this in `application.conf`, but it didn't work:

```
slick.dbs.default.db.driver = "org.h2.Driver"
slick.dbs.default.db.url = "jdbc:h2:mem:play"
slick.dbs.default.db.user = ""
slick.dbs.default.db.password = ""
```

With the error message `Cannot connect to database [default]` on the line `slick.dbs.default.db.driver = "org.h2.Driver"`

Since I'm a beginner to Scala, Play and Slick it's not particularly obvious what to do next -- do you have any ideas?

**Comment by pedrorijo91** [comment]
Hey,

Unfortunately I still hadn't the time to have a look. I will try to find some free time soon, and hope to have something in a couple of days.

In the meanwhile, can you put here the output?

If you find a solution until then, please share. Maybe we can add that information to the README, or create another branch with the tutorial H2 version.

**Comment by cabalamat** [comment]
No, I've not managed to get it working. I changed to using Postgres
(because that is what I will be using on my web app that I am writing), and
after sorting out many things I can now get the program to talk to the
database, because Evolutions is creating the User table there.

However I there is another error -- when I run the web app it produces
loads of error messages on the postgres log file like this:

```
2016-03-22 10:28:42 GMT FATAL:  sorry, too many clients already
```

this suggests to me that I am creating loads of connections and not closing
them. I wonder if you have any ideas as to what might be causing this?

On 21 March 2016 at 23:37, Pedro Rijo notifications@github.com wrote:

> Hey,
> 
> Unfortunately I still hadn't the time to have a look. I will try to find
> some free time soon, and hope to have something in a couple of days.
> 
> In the meanwhile, can you put here the output?
> 
> If you find a solution until then, please share. Maybe we can add that
> information to the README, or create another branch with the tutorial H2
> version.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/pedrorijo91/play-slick3-steps/issues/1#issuecomment-199537699

## 

Phil Hunt, cabalamat@gmail.com

**Comment by pedrorijo91** [comment]
for H2, I managed to connect, using [these changes](https://github.com/pedrorijo91/play-slick3-steps/commit/024aa59d1afbdcf286cb05d81021c48e96474f59)

Still, there's a problem applying the evolutions, that should be due to different a SQL syntax used by H2.

For your problem with psql connection, may be due to some setting on the psql database you installed. I recommend you to check this thread on SO that may help: http://stackoverflow.com/questions/9798705/arval-sqlexception-fatal-sorry-too-many-clients-already-in-postgres

**Comment by pedrorijo91** [comment]
just pushed some [more changes](https://github.com/pedrorijo91/play-slick3-steps/commit/0a7a80eef91b791e366e7f5cd61c414bcd8c5793) (read [this tutorial](http://www.lightbend.com/activator/template/play-slick)), and everything seems to be working
