### ISSUE TITLE
Compilation error[play.api.mvc.Call does not take parameters]

### ISSUE THREAD

**Issue by pratham-0709** [pedrorijo91/play-slick3-steps#13]
Hello there, 

 I am new to Scala and was trying and performing CRUD operations in Scala using play framework and Slick while performing I came across this issue for which image has been attached for your reference .

![image](https://github.com/pedrorijo91/play-slick3-steps/assets/53365574/9016bc33-6a93-4d81-a323-0c162d3e02b6)

what could be the possible reason of this ? 

Likely , using your code for understanding the flow also attaching the image for your reference 

![image](https://github.com/pedrorijo91/play-slick3-steps/assets/53365574/011167eb-2f21-4022-a778-758bcdcf3932)

Do let me know , 

Thanks

**Comment by pedrorijo91** [comment]
hey @pratham-0709 

hard to tell without seeing the full code. my guess is that it may be some issue with versions. likely u are using a different play version than the one in this repo

are you able to run the code in this repo after cloning it?

**Comment by pratham-0709** [comment]
Hello [pedrorijo91](https://github.com/pedrorijo91)
Thanks for responding, I am using the different version of Play ( 2.8.0) would share the build.sbt and application.conf for better understanding to it , rest the code is same as previously mentioned in the comment . 

![image](https://github.com/pedrorijo91/play-slick3-steps/assets/53365574/5b1abe55-8712-4f1e-9fb7-df567536dcfd)

![image](https://github.com/pedrorijo91/play-slick3-steps/assets/53365574/0cfca3c3-9db1-4a71-be0f-d56bc124c965)

Do let me know , 
Thanks

**Comment by pedrorijo91** [comment]
if the Play version is different, it's very likely the signature of some methods have changed. I haven't touched Play for a while, but check their documentation under https://www.playframework.com/documentation/2.8.x/Migration28 to see if there's any help.

Play framework has a long record of doing many breaking changes in each release, which is a huge headache 🤷

**Comment by pratham-0709** [comment]
Hello [pedrorijo91](https://github.com/pedrorijo91)

Thanks for responding , totally understandable about the thing you have mentioned about version.
Will check once again . 

Thanks for the support.
