### ISSUE TITLE
Service Redundancy

### ISSUE THREAD

**Issue by jmcardon** [pedrorijo91/play-slick3-steps#5]
Hi! First off I'd like to say thank you for the example, it really helped me understand the play-slick migration and the JDBC connectivity when I was just picking up the framework.

I was thinking whether the accessing through the service is now a redundant pattern. Now the DB access class that imports the config through the AppProvider is being instantiated as a Singleton, I see no reason for the Service pattern as yet another instance to access the singleton and consume unnecessary memory.

If you agree, I can send a pull request of the example with the service pattern removed.

**Comment by pedrorijo91** [comment]
Hi @jmcardon . I'm glad this example helped you to better understand this framework.

While in this example the service layer is redundant, in other applications it may contain more logic, hence it's inclusion. It will also allow more easily to use this code as skeleton for other developers who want a starting point.

Finally, as a novice tutorial, memory consumption is not a very relevant concern. I do think this architecture provides a set of good practices, without overengineering.

**Comment by jmcardon** [comment]
Thank you for your response! I'll be closing this issue then
